server:
  port: 8000

spring:
  application:
    name: currency-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: currency-db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
