server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: currency-service
          uri: lb://currency-service
          predicates:
            - Path=/currency-service/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**

management:
  tracing:
    sampling:
      probability: 1.0